Zuber/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Zuber.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Zuber/Pages/GetProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Zuber.Models;
using Zuber.Services.EFServices;
using Zuber.Services.Interfaces;

namespace Zuber.Pages
{
    public class GetProfileModel : PageModel
    {
        public IUserService service;
        public SingletonUser User;
        [BindProperty]
        public ZuberUser GetUser { get; set; }
        public GetProfileModel(SingletonUser s,IUserService i)
        {
            User = s;
            service = i;
            
        }
        public IActionResult OnGet(int id)
        {
            if (User.SignedIn)
            {
                GetUser = service.GetZuberUserById(id);
                return Page();
            }
            else
            {
                return RedirectToPage("Login");
            }
        }
    }
}

Zuber/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Zuber.Services.EFServices;

namespace Zuber.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public SingletonUser User;

        public IndexModel(ILogger<IndexModel> logger, SingletonUser s)
        {
            _logger = logger;
            User = s;
        }

        public IActionResult OnGet()
        {
            //if (User.User==null)
            if (!User.SignedIn)
            {
                return RedirectToPage("Login");
            }
            return Page();
        }
    }
}

Zuber/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Zuber.Models;
using Zuber.Services.EFServices;
using Zuber.Services.Interfaces;

namespace Zuber.Pages
{
    public class LoginModel : PageModel
    {
        IUserService service;
        public SingletonUser User;
        [BindProperty]
        public ZuberUser input { get; set; }
        [BindProperty]
        public bool failedLogin { get; set; }
        public LoginModel(IUserService s, SingletonUser su)
        {
            service = s;
            User = su;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            ZuberUser user = service.GetZuberUser(input.Email);
            if (user != null && EFUserService.CheckHashedPassword(user.Email, user.Password, input.Password))
            {
                User.Login(user);
                //IdentityService.Identity.Login(user);
                return RedirectToPage("Index");
            }
            failedLogin = true;
            return Page();
        }
    }
}

Zuber/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Zuber.Services.EFServices;

namespace Zuber.Pages
{
    public class LogoutModel : PageModel
    {
        public SingletonUser User;
        public LogoutModel( SingletonUser s)
        { 
            User = s;
        }
        public IActionResult OnGet()
        {
            User.Logout();
            return RedirectToPage("Login");
        }
    }
}

Zuber/Pages/MapView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Zuber.Models;
using Zuber.Services.EFServices;
using Zuber.Services.Interfaces;

namespace Zuber.Pages
{
    public class MapViewModel : PageModel
    {
        public SingletonUser User;
        public IDotService dService;
        public JsonDotService jSon;
        
        //[BindProperty]
        //public List<Dot> Dots { get; set; }
        public MapViewModel( SingletonUser s, IDotService d,JsonDotService j)
        {
            User = s;
            dService = d;
            //Dots = d.GetAllDots();
            jSon = j;
            jSon.UpdateJson();
        }
        public IActionResult OnGet()
        {
            //if (!User.SignedIn)
            //{
            //    return RedirectToPage("Login");
            //}
            return Page();
        }
    }
}

Zuber/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Zuber.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Zuber/Pages/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Zuber.CustomAtributes;
using Zuber.Models;
using Zuber.Services.EFServices;
using Zuber.Services.Interfaces;

namespace Zuber.Pages
{
    public class ProfileModel : PageModel
    {
        //private readonly Zuber.Pages.Data.ImageContext _context;
        //private readonly IWebHostEnvironment _iweb;

        public IUserService service;
        public SingletonUser User;
        [BindProperty]
        public ZuberUser editableUser { get; set; }
        public ProfileModel(SingletonUser s,IUserService i)
        {
            User = s;
            service = i;
            
        }
        public IActionResult OnGet()
        {
            if (User.SignedIn)
            {
                editableUser = User.User;
                return Page();
            }
            //Anything
            else
            {
                return RedirectToPage("Login");
            }
        }
        public IActionResult OnPostSave()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            service.UpdateZuberUser(editableUser);
            User.Login(editableUser);
            if (editableUser.Driver)
            {
                return RedirectToPage("dotSettings");
            }

            return RedirectToPage("Index");
        }

        public IActionResult OnPostDelete()
        {
            service.DeleteZuberUser(User.User.Email);
            return RedirectToPage("Logout");
        }
        
       //{
       //     private readonly Zuber.Pages.Data.ImageContext _context;
       //     private readonly IWebHostEnvironment _iweb;

       //     public ProfileModel(RazorPages_CRUD_Fileupload.Data.ImageContext context, IWebHostEnvironment iweb)
       //     {
       //         _context = context;
       //         _iweb = iweb;

       //     }

       //     public IList<Imagesave> Imagesave { get; set; }

       //     public async Task OnGetAsync()
       //     {
       //         Imagesave = await _context.Imagesave.ToListAsync();
       //     }

       //     public async Task<IActionResult> OnPostAsync(IFormFile uploadfiles, Imagesave img)
       //     {
       //         if (!ModelState.IsValid)
       //         {
       //             return Page();
       //         }

       //         string imgext = Path.GetExtension(uploadfiles.FileName);
       //         if (imgext == ".jpg" || imgext == ".png")
       //         {
       //             var imgsave = Path.Combine(_iweb.WebRootPath, "Images", uploadfiles.FileName);
       //             var stream = new FileStream(imgsave, FileMode.Create);
       //             await uploadfiles.CopyToAsync(stream);
       //             stream.Close();

       //             img.Imgname = uploadfiles.FileName;
       //             img.Imgpath = imgsave;
       //             await _context.Imagesave.AddAsync(img);
       //             await _context.SaveChangesAsync();
       //         }

       //         return RedirectToPage("./Index");
       //     }
        //}
    }
}

Zuber/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Zuber.Models;
using Zuber.Services.EFServices;
using Zuber.Services.Interfaces;
using Zuber.CustomAtributes;

namespace Zuber.Pages
{
    public class RegisterModel : PageModel
    {
        public class InputModel
        {
            [Required]
            [RegularExpression(@"^[A-Za-z]+\s?[A-Za-z]*$",ErrorMessage ="Please, insert your name using only letters")]
            public string Name { get; set; }
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            [RegularExpression(@"^([\w\.\-]+)@([\w\-\.]+)((\.(\w){2,3})+)$", ErrorMessage = "Please, enter valid email adress")]
            //[RegularExpression(@"^[A-Z0-9a-z._%+-]+@[A-Z0-9a-z.-]+\.[A-Za-z]{2,}$.", ErrorMessage = "Please, enter valid email adress")]
            //[RegularExpression(@"^[A-Z0-9a-z._%+-]+@edu\.easj\.dk"),ErrorMessage ="Please, enter your Zealand email adress"] version for zealand students mails
            //[RegularExpression(@"^[a-z]{4}[0-9]{4}@edu\.easj\.dk"),ErrorMessage ="Please, enter your Zealand email adress] stricter version for studentmails
            public string Email { get; set; }
            
            [Required]
            [Phone]
            [RegularExpression(@"^\+?[0-9]{3,15}$", ErrorMessage = "Please, enter valid phone number")]
            public string PhoneNo { get; set; }
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            [PasswordFoolproof("Name","Email","PhoneNo")]
            public string Password { get; set; }
            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
            public bool Driver { get; set; }
        }
        IUserService service;
        SingletonUser User;
        [BindProperty]
        public InputModel newUser { get; set; }
        public RegisterModel(IUserService i, SingletonUser u)
        {
            service = i;
            User = u;
        }
        public void OnGet()
        {
            
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            ZuberUser NewToDatabase = new ZuberUser();
            NewToDatabase.Name = newUser.Name;
            NewToDatabase.Email = newUser.Email;
            NewToDatabase.PhoneNo = newUser.PhoneNo;
            NewToDatabase.Password = newUser.Password;
            NewToDatabase.Driver = newUser.Driver;
            service.AddZuberUser(NewToDatabase);
            User.Login(service.GetZuberUser(NewToDatabase.Email));
            return RedirectToPage("dotSettings");
        }
    }
}

Zuber/Pages/dotSettings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Zuber.Models;
using Zuber.Services.EFServices;
using Zuber.Services.Interfaces;

namespace Zuber.Pages
{
    public class dotSettingsModel : PageModel
    {
        public SingletonUser User;
        public IDotService dService;

        public IUserService uService;
        public IRideService rService;
        [BindProperty]
        public Dot userDot{get;set;}
        [BindProperty]
        public Ride userRide { get; set; }

        public dotSettingsModel(SingletonUser s, IDotService d, IRideService r,IUserService u) { 
            User = s;
            dService = d;
            rService = r;
            uService = u;
        }
        public IActionResult OnGet(double latitude, double longitude)
        {
            if (!User.SignedIn)
            {
                return RedirectToPage("Login");
            }
            
            if (!User.User.DotId.HasValue)
            {
                userDot = new Dot();
                //userDot.ZuberUserID = User.User.Id;
                userDot.Lat = latitude;
                userDot.Long = longitude;
            }
            else
            {
                userDot = dService.GetDotById(User.User.DotId.Value);
                if (latitude != 0 && longitude != 0)
                {
                    userDot.Lat = latitude;
                    userDot.Long = longitude;
                }
                
            }
            if (User.IsDriver)
            {
                if(!User.User.RideId.HasValue)
                   userRide = new Ride();
                else { 
                    userRide = rService.GetRideById(User.User.RideId.Value); 
                }
            }
            
            return Page();
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            userDot.ZuberUserID = User.User.Id;
            if (User.User.DotId.HasValue)
            {
                dService.UpdateDot(userDot);
            }
            else 
            { 
                dService.AddDot(userDot); 
                Dot d = dService.GetDotByUserId(User.User.Id);
                uService.GiveUserDot(User.User, d.Id);
                User.Login(uService.GetZuberUserById(User.User.Id));
            }
            if (User.IsDriver)
            {
                userRide.DriverId = User.User.Id;
                if (User.User.RideId.HasValue)
                {
                    rService.UpdateRide(userRide);
                }
                else
                {
                    rService.AddRide(userRide);
                    Ride r = rService.GetRideByUserId(User.User.Id);
                    User.User.RideId = r.Id;
                    uService.UpdateZuberUser(User.User);
                    User.Login(uService.GetZuberUserById(User.User.Id));
                }
            }
            return RedirectToPage("Index");
        }

    }
}

Zuber/Pages/GetProfile.cshtml
@page
@model Zuber.Pages.GetProfileModel
@{
}

<body style="background-image: url(" Images /bg-1.jpg"); margin: 0; padding: 0; background-size: cover; background-position: center; font-family: sans-serif; color: #fff;">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-10 mt-5 pt-5">
                <div class="row z-depth-3">
                    <div class="col-sm-4 bg-dark rounded-left">
                        <img src="Images/15.jpg" class="img-fluid rounded-circle" alt="img 1">
                        <div class="card-block text-center text-white">
                            <i class="fas fa-user-tie fa-7x mt-5"></i>
                            <h2 class="font-weight-bold mt-4">bla bla</h2>
                            <p>bla bla2</p>
                            <i class="far fa-edit fa-2x mb-4"></i>
                        </div>
                    </div>
                    <div class="col-sm-8 bg-white rounded-right">
                        <h3 class="mt-3 text-center">@Model.User.User.Name's Profile</h3>
                        <hr class="badge-primary mt-0 w-25">
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="font-weight-bold">Name:</p>
                                <h6 class="text-muted">@Model.GetUser.Name</h6>
                            </div>
                            <div class="col-sm-6">
                                <p class="font-weight-bold">Status</p>
                                @{
                                    if (@Model.GetUser.Driver)
                                    {
                                        <h6 class="text-muted">Driver</h6>
                                    }
                                    else if (!@Model.GetUser.Driver)
                                    {
                                        <h6 class="text-muted">Passenger</h6>
                                    }
                                }
                            </div>
                        </div>
                        <h4 class="mt-3">Contact</h4>
                        <hr class="bg-primary">
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="font-weight-bold">Phone</p>
                                <h6 class="text-muted">@Model.GetUser.PhoneNo</h6>
                            </div>
                            <div class="col-sm-6">
                                <p class="font-weight-bold">Email</p>
                                <h6 class="text-muted">@Model.GetUser.Email</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

Zuber/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: url(/wwwroot/Images/14.jpg);
            background-repeat: no-repeat;
            height: 100%;
            margin: 0;
            padding: 0;
            background-size: cover;
            background-position: center;
            font-family: sans-serif;
            color: #fff;
        }
.containerr{
    text-align: center;
    position: absolute;
    top: 50%;
    left: 50%;
    transform:translate(-50%,-50%);
    width: 100% ;
}
.containerr h1{
    color:white;
    text-transform: uppercase;
    display:block;

}
.text1{
    color: white;
    font-size: 60px;
    font-weight: 700;
    letter-spacing: 8px;
    margin-bottom:20px;
    background:black;
    position:relative;
    animation: text 3s 1;
}
.text2{
    font-size: 30px;
    color:#6ab04c;
}
@@keyframes text{
    0%{
        color: black;
        margin-bottom:-40px;
}
70%{
    letter-spacing: 25px;
margin-bottom:-40px;
}}
    </style>
    </head>
<body style="background-image: url(/images/36.jpg.jpeg); margin: 0; padding: 0; background-size: cover; background-position: center; font-family: sans-serif; color: #fff;">
<main class="container" style="height: 100vh;">
    <div class="containerr">
        
        @if (Model.User.IsDriver && Model.User.SignedIn)
        {

            <h1 class="text1">Yo Driver</h1>
            <h1 class="text2">Zuber 2021</h1>
        }
        else
        {
            <h1 class="text1">Yo Passenger</h1>
            <h1 class="text2">Zuber 2021</h1>

        }
        </div>
    </body>
</html>


@*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@

Zuber/Pages/Logout.cshtml
@page
@model Zuber.Pages.LogoutModel
@{
}

Zuber/Pages/Profile.cshtml
@page
@model Zuber.Pages.ProfileModel
@{
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>

    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.1.0/css/bootstrap-switch-button.min.css" rel="stylesheet">

</head>

</html>
<body style="background-image: url(/Images/bg-1.jpg); background-size: cover;">
<main class="container" style="height: 100vh;">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="@Model.editableUser.Id"/>
                <input type="hidden" asp-for="@Model.editableUser.Password"/>
                <input type="hidden" asp-for="@Model.editableUser.Email"/>
                <input type="hidden" asp-for="@Model.editableUser.DotId"/>
                <div class="col-md-10 mt-5 pt-5">
                    <div class="row z-depth-3">
                        <div class="col-sm-4 bg-dark rounded-left">
                            <img src="Images/15.jpg" class="img-fluid rounded-circle" alt="img 1">
                            <div class="card-block text-center text-white">
                                <i class="fas fa-user-tie fa-7x mt-5"></i>
                                <input type="file" name="file" id="file" class="inputfile"/>
                                <label for="file">Choose a file</label>

                                <i class="far fa-edit fa-2x mb-4"></i>
                            </div>
                        </div>
                        <div class="col-sm-8 bg-light rounded-right text-white">
                            <h3 class="mt-3 text-center">Information</h3>
                            <hr class="badge-primary mt-0 w-25">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label class="font-weight-bold" asp-for="@Model.editableUser.Name"></label>
                                    <input asp-for="@Model.editableUser.Name" class="form-control"/>
                                    <span asp-validation-for="@Model.editableUser.Name" class="text-danger"></span>
                                </div>
                                <div class="col-sm-6">
                                    <p class="font-weight-bold">Status</p>
                                    <div class="custom-control custom-switch">

                                        <style>
                                            .switch.ios, .switch-on.ios, .switch-off.ios {
                                                border-radius: 20rem;
                                            }

                                            .switch.ios .switch-handle {
                                                border-radius: 20rem;
                                            }
                                        </style>
                                        <input type="checkbox" data-toggle="switchbutton" data-style="ios" data-onstyle="dark" data-onlabel="Driver" data-offlabel="Passenger" asp-for="@Model.editableUser.Driver">

                                        @*<input type="checkbox" class="custom-control-input" id="switch" asp-for="@Model.editableUser.Driver">
                                <label class="custom-control-label" for="switch">Passenger, Driver</label>*@
                                    </div>
                                </div>
                            </div>
                            <h4 class="mt-3">Contact</h4>
                            <hr class="bg-primary">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label class="font-weight-bold" asp-for="@Model.editableUser.PhoneNo"></label>
                                    <input asp-for="@Model.editableUser.PhoneNo" class="form-control"/>
                                    <span asp-validation-for="@Model.editableUser.PhoneNo" class="text-danger"></span>
                                </div>
                                <div class="col-sm-6">
                                    <label class="font-weight-bold" asp-for="@Model.editableUser.Email"></label>
                                    <input class="form-control" value="@Model.editableUser.Email" disabled/>
                                </div>
                            </div>
                            <hr/>

                            <div class="row">
                                <div class="col-sm-4">
                                    <button class="btn btn-danger" asp-page-handler="Delete" onclick="deleteProfile()">Delete Profile</button>
                                </div>
                                <div class="col-sm-4">
                                    <button class="btn btn-group-lg" asp-page="dotSettings">Set your dot</button>
                                </div>
                                <div class="col-sm-4">
                                    <input type="submit" value="Save" asp-page-handler="Save" class="btn btn-primary"/>
                                </div>
                            </div>
                            <br/>

                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</main>
@*<footer class="navbar navbar-default navbar-static-bottom">
    
</footer>*@

<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.1.0/dist/bootstrap-switch-button.min.js"></script>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
</body>


<script>
    function deleteProfile() {
        if (!confirm("Are you sure? This is permanent.")) {
            event.preventDefault();
        }
    }
</script>

Zuber/Pages/dotSettings.cshtml
@page
@model Zuber.Pages.dotSettingsModel
@{
}
<body style="background-image:url(/Images/1.png); margin:0; padding:0; background-size: cover;background-position:center;font-family: sans-serif; color: #fff;">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12"></div>
            <div class="col-md-4 col-sm-4 col-xs-12">

                <form method="post" style="border: 0px solid #fff; padding: 20px; border-radius: 10px; margin-top: 8vh;-webkit-box-shadow: -1px 4px 26px 19px rgba(0,0,0,0.75);
                -moz-box-shadow: -1px 4px 26px 19px rgba(0,0,0,0.75);
                box-shadow: -1px 4px 26px 19px rgba(0,0,0,0.75);" class="form-container">
                    @*<h1 style="text-align: center;">Use The Map</h1>*@
                    @*<form method="post">*@
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="@Model.userDot.Id" />
                        <p>Please insert coordinates of the place where you want to be picked up <br /> You can input them manually or you can <br /> <a asp-page="MapView">Use the Map</a></p>
                        <div class="form-group">
                            <label asp-for="@Model.userDot.Lat" class="control-label"></label>
                            <input asp-for="@Model.userDot.Lat" class="form-control" />
                            <span asp-validation-for="@Model.userDot.Lat" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.userDot.Long" class="control-label"></label>
                            <input asp-for="@Model.userDot.Long" class="form-control" />
                            <span asp-validation-for="@Model.userDot.Long" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.userDot.Time" class="control-label"></label>
                            <input type="time" asp-for="@Model.userDot.Time" class="form-control" />
                            <span asp-validation-for="@Model.userDot.Time" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.userDot.Description" class="control-label"></label>
                            <input asp-for="@Model.userDot.Description" class="form-control" />
                            <span asp-validation-for="@Model.userDot.Description" class="text-danger"></span>
                        </div>
                        <div class="custom-control custom-switch">

                            <input type="checkbox" class="custom-control-input" id="switch" asp-for="@Model.userDot.Hidden">
                            <label class="custom-control-label" for="switch">do you want to hide your dot?</label>
                        </div>
                        @if (Model.User.IsDriver)
                        {
                            <h3>Ride properties</h3>
                            <div class="form-group">
                                <label asp-for="@Model.userRide.PlacesRemaining" class="control-label"></label>
                                <input asp-for="@Model.userRide.PlacesRemaining" class="form-control" />
                                <span asp-validation-for="@Model.userRide.PlacesRemaining" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="@Model.userRide.CarDescription" class="control-label"></label>
                                <input asp-for="@Model.userRide.CarDescription" class="form-control" />
                                <span asp-validation-for="@Model.userRide.CarDescription" class="text-danger"></span>
                            </div>

                        }
                        <div class="form-group">
                            <input type="submit"  value="Save" asp-page-handler="Save" class="btn btn-success " />
                        </div>

                    </form>
                </div>
            </div>
        </body>